### PR TITLE
Meteor 2.13 support

### PR DESCRIPTION
**Pull request by jdgjsag67251**
Fixes https://github.com/zodern/meteor-docker/issues/32

### CODE REVIEW

**Comment by KoenLav** [comment]
@zodern could you take a look at see if this can be merged? Would be nice to be able to deploy Meteor 2.13 using meteor-up!

**Comment by jdgjsag67251** [comment]
While you are waiting for this to get merged, you could use our custom image: https://hub.docker.com/r/duodeka/meteor.

**Comment by aboire** [comment]
@jdgjsag67251 I got this error using your image to deploy
```
[51.210.124.253] x Prepare Bundle: FAILED

              ------------------------------------STDERR------------------------------------
              The command '/bin/sh -c bash ./scripts/onbuild-node.sh' returned a non-zero code: 1

        real    0m47.925s
        user    0m6.117s
        sys     0m11.075s

              ------------------------------------STDOUT------------------------------------
               complete
        ee817e3b4b2d: Verifying Checksum
        ee817e3b4b2d: Download complete
        4f4fb700ef54: Verifying Checksum
        4f4fb700ef54: Download complete
        14726c8f7834: Download complete
        bcef4c00199b: Verifying Checksum
        bcef4c00199b: Download complete
        30ae837a2be5: Verifying Checksum
        30ae837a2be5: Download complete
        ce18bdd4f4c8: Verifying Checksum
        ce18bdd4f4c8: Download complete
        f275b4dde9aa: Verifying Checksum
        f275b4dde9aa: Download complete
        6eb22128b276: Verifying Checksum
        6eb22128b276: Download complete
        f57c9d7628ac: Verifying Checksum
        f57c9d7628ac: Download complete
        78f673cfc09e: Verifying Checksum
        78f673cfc09e: Download complete
        55e784467817: Verifying Checksum
        55e784467817: Download complete
        185e4cde5462: Verifying Checksum
        185e4cde5462: Download complete
        14726c8f7834: Pull complete
        55e784467817: Pull complete
        4c3d44116e18: Pull complete
        ee817e3b4b2d: Pull complete
        4f4fb700ef54: Pull complete
        bcef4c00199b: Pull complete
        30ae837a2be5: Pull complete
        6eb22128b276: Pull complete
        ce18bdd4f4c8: Pull complete
        f275b4dde9aa: Pull complete
        f57c9d7628ac: Pull complete
        78f673cfc09e: Pull complete
        185e4cde5462: Pull complete
        Digest: sha256:f80e59c25a8770763d3c4d9b60f309e97459bd79172462512291590186561024
        Status: Downloaded newer image for duodeka/meteor:root
        docker.io/duodeka/meteor:root
        Preparing for docker build
        Creating Dockerfile
        Finished creating Dockerfile
        Building image
        Sending build context to Docker daemon   1.31GB
        Step 1/16 : FROM duodeka/meteor:root
        # Executing 6 build triggers
         ---> Running in c02a1323946c
        Removing intermediate container c02a1323946c
         ---> Running in 573b53360427
        Removing intermediate container 573b53360427
         ---> Running in 7b0638c98444
        Removing intermediate container 7b0638c98444
         ---> Running in 7f4f4a9b26be
        NODE_VERSION=14.21.4
        Node: 14.21.4
        Major: 14
        Minor: 21
        Using Meteor's custom NodeJS v14 LTS version
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
100 32.6M  100 32.6M    0     0  13.7M      0  0:00:02  0:00:02 --:--:-- 13.7M
        N/A: version "v14.21.4" is not yet installed.

        You need to run "nvm install v14.21.4" to install it before using it.
        dirname: missing operand
        Try 'dirname --help' for more information.

              ------------------------------------------------------------------------------
```

**Comment by vachigaggl** [comment]
Workaround while this is pending:

according to https://forums.meteor.com/t/announcing-extended-support-maintenance-for-node-js-14/59811/9
the officially supported image is:
[Meteor NodeJS 23](https://github.com/zcloud-ws/zcloud-community-images/tree/main/meteor-tools/meteor-node-runtime/README.md): Nodejs runtime from Meteor and Compatible with MUP

**Comment by aboire** [comment]
@vachigaggl Are you deploying rocketchat with this image?

**Comment by ferjep** [comment]
> While you are waiting for this to get merged, you could use our custom image: https://hub.docker.com/r/duodeka/meteor.

This image has this line commented out
https://github.com/zodern/meteor-docker/blob/076a7ea1a128e419d90b6b4ad74bb3a01be6d4e5/image/scripts/start.sh#L15

**Comment by ferjep** [comment]
For anyone who has built @jdgjsag67251 root image, and it's throwing this error, https://github.com/zodern/meteor-docker/pull/34#issuecomment-1742532173 (@aboire)

Basically, root-image/Dockerfile is extending the current `zodern/meteor` and you're not really using @jdgjsag67251 fix.

1. `cd image/` and build that base image `docker build --no-cache -t jdgjsag67251/meteor .`
2. `vim root-image/Dockerfile`, replace the first line that uses @zodern image by the one that you just built `FROM jdgjsag67251/meteor`. If you used another tag name for the first step, use that one then
3. `cd root-image/` and build the root image  `docker build --no-cache -t jdgjsag67251/meteor:root .`

**Comment by MomenYasser** [comment]
For everyone facing the problem, till this PR is merged you can my custom image `momenysr/meteor:root` and your problem will be solved.

in `mup.js` file:
```javascript
...
docker: {
    image: 'momenysr/meteor:root',
}
....
```

**Comment by generalleger** [comment]
> For everyone facing the problem, till this PR is merged you can use my custom image `momenysr/meteor:root` and your problem will be solved.
> 
> in `mup.js` file:
> 
> ```js
> ...
> docker: {
>     image: 'momenysr/meteor:root',
> }
> ....
> ```

Thank you! That worked for me.

**Comment by nicooler** [comment]
Thank you for sharing @MomenYasser 

`> > docker: {
> >     image: 'momenysr/meteor:root',
> > }
> > ....
> > `


The app does start with this image, but the  buildInstructions: [... 
are not running. Took me a while to realise it. Not sure why though.

**Comment by aboire** [comment]
Does anyone find a solution or a working image in root with buildInstructions ?

**Comment by u-sour** [comment]
> While you are waiting for this to get merged, you could use our custom image: https://hub.docker.com/r/duodeka/meteor.

it works , thank 🚀

**Comment by ivan133** [comment]
I'm sorry which image should I use for meteor 2.13?

**Comment by zodern** [comment]
Any of the tags published since this PR was merged supports Meteor 2.13. For example: `latest`, `root`, `0.7.1`, `0.7.1-root`.

**Pull request merged**
